FROM node:18-alpine3.17 as prune

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY package*.json ./

RUN yarn

COPY . .

RUN yarn turbo prune --scope @apps/api --docker
RUN rm -rf /usr/src/app/node_modules

FROM node:18-alpine3.17 as production

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY --from=prune /usr/src/app/out/json/ /usr/src/app/

RUN yarn

COPY . .

RUN yarn build:api

RUN yarn workspace @apps/api prisma generate

COPY ./index.js .

CMD ["yarn", "start:api"]