version: '3.9'

services:
  api:
    image: 'filmania-api:latest'
    env_file:
      - ./.env
    ports:
      - 3000:3000
    networks:
      - app_network
    restart: always
    depends_on:
      - db
      - redis

  db:
    image: 'postgres:14'
    restart: always
    environment:
      - PGUSER=root
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpass
      - POSTGRES_DB=dbname
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - .docker/db:/var/lib/postgresql/data:rw
    ports:
      - 7732:5432
    networks:
      - app_network
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready' ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    platform: linux/amd64
    image: 'bitnami/redis'
    restart: always
    ports:
      - 7779:6379
    networks:
      - app_network
    environment:
      - ALLOW_EMPTY_PASSWORD=true
    volumes:
      - redis_data:/data

volumes:
  redis_data:


networks:
  app_network:
    driver: bridge
